### ISSUE TITLE
Update AlohaThreatZone info

### ISSUE THREAD

**Issue by rscheitlin** [gavinr/wab-widget-search#15]
![alohathreatzonewidget](https://user-images.githubusercontent.com/1216460/52792275-9782b580-3030-11e9-9b30-cfcbb89af1a6.jpg)

Thumbnail image provided

Expanded Desc:
If you are an emergency responder than you are likely familiar with NOAA'a ALOHA 
(Areal Locations of Hazardous Atmospheres) is a modeling program that estimates threat zones associated with hazardous chemical releases, including toxic gas clouds, fires, and explosions. 

This widget does not model or generate the chemical plume, It only imports the Aloha .pas
file and parses the file to plot the data in Web AppBuilder.

**Comment by gavinr** [comment]
@rscheitlin thanks so much for submitting updates on all these. I'll definitly update the thumbnails you've been posting.

One note about the descriptions - the site pulls these from your `manifest.json` file, so you can actually update these yourself. You can find the manifest.json URLs I'm using here: https://github.com/gavinr/wab-widget-search/blob/master/public/widgets.json

.. for example, for AlohaThreat, it's using the manifest here: https://gis.calhouncounty.org/WAB/V2.9/widgets/Aloha/widgets/AlohaThreatZone/manifest.json

**Comment by rscheitlin** [comment]
Gavin,
   Thanks. I did not realize that was coming from the manifest.json.

**Comment by gavinr** [comment]
No problem! Note that after you change it, it may take a few minutes until the changes show up on the site.

**Comment by gavinr** [comment]
Image added
