### ISSUE TITLE
MapProgress Widget

### ISSUE THREAD

**Issue by rscheitlin** [gavinr/wab-widget-search#17]
Thumbnail:
![mapprogresswidget](https://user-images.githubusercontent.com/1216460/52791292-3e198700-302e-11e9-94c9-919432b2abf9.jpg)

Updated Desc:
A map progress indicator that is more visible to the user. The animated icon is configurable by the user so that company branding can occur.

**Comment by gavinr** [comment]
Image added. Thanks!
