### ISSUE TITLE
Popup Panel Widget Update

### ISSUE THREAD

**Issue by rscheitlin** [gavinr/wab-widget-search#18]
Thumbnail:
![popuppanelwidget](https://user-images.githubusercontent.com/1216460/52791747-4920e700-302f-11e9-9ecf-0247695cf513.jpg)

Updated Desc:
For those of you that don't want the popup to block features on the map or wish you could have selections results info displayed some where beside the map info window, this is the widget for you.

**Comment by gavinr** [comment]
Image added. Thanks!
